---
- name: Include vCenter variables 
  include_vars: ../group_vars/vcenter.yml 

- name: Copy vsphere script file
  win_copy: 
    src: templates/movevdisk.ps1 
    dest: c:\ANSIBLE\
  delegate_to: seplmovcs02
  when: 
    - vdiskname2firsttime == true
    - vdiskname2attachpersistent == false

- name: Move virtual disk of {{ CompHost }} to dedicated datastore {{ vdatastore2 }}
  win_shell: c:\ANSIBLE\movevdisk.ps1 -CompHost {{ CompHost }} -vstore "{{ vdatastore2 }}" -vdisk "{{ vdiskfile2 }}" -vdiskname2 "{{ vdiskname2 }}"
  register: move_disk_result
  delegate_to: seplmovcs02
  when: 
    - vdiskname2firsttime == true
    - vdiskname2attachpersistent == false

- debug: msg="{{ move_disk_result.stdout_lines }}"
  when: 
    - vdiskname2firsttime == true
    - vdiskname2attachpersistent == false