---
- name: Include vCenter variables
  include_vars: ../group_vars/vcenter.yml

- name: Reconfigure network on {{ CompHost }} image
  vmware_guest:
    hostname: vcs01.lab.local
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    folder: "{{ vfolder }}"
    datacenter: "{{ vdatacenter }}"
    esxi_hostname: "{{ esxhost }}"
    name: "{{ CompHost }}"
    networks:
    - name: "{{ vnetwork1 }}"
      ip: "{{ vip1 }}"
      netmask: "{{ vmask1 }}"
      gateway: "{{ vgateway1 }}"
      domain: "{{ CompDomain }}"
      type: "{{ iftype1 }}"
      dns: "{{ vdnsservers }}"
    - name: "{{ vnetwork2 }}"
      ip: "{{ vip2 }}"
      netmask: "{{ vmask2 }}"
      gateway: "{{ vgateway2 }}"
      type: "{{ iftype2 }}"
    wait_for_ip_address: yes
  delegate_to: localhost
  when: 
    - nicsTotal == 2
