#### CONNECTION PARAMETERS
#ansible_port: 5985
#ansible_port: 5986
ansible_port: 22
#ansible_connection: winrm
ansible_connection: ssh
#ansible_connection: kerberos
ansible_winrm_server_cert_validation: ignore
#ansible_winrm_server_cert_validation: true

#### SERVER PARAMETERS
CompHost: APP01
CompDomain: lab.local
os: LINUX
#os: WINDOWS 


#### VCENTER PARAMETERS
vdatacenter: WARSAW
vfolder: /vm/Linux
esxhost: esx01.lab.local
vtemplate: IMGCentos

#### DNS ADDRESSING
vdns1: 192.168.0.201
vdns2: 8.8.8.8

#### IP ADDRESSING
vnetwork1: "VM Network"
iftype1: static
#iftype1: dhcp
vip1: 192.168.0.206
vmask1: 255.255.255.0
vgateway1: 192.168.0.1

