---
- hosts: localhost
  gather_facts: no

  roles:
#    - GITHUB

- hosts: [app01]
  gather_facts: no

  roles:
    - AD_group_add
    - IMAGE_deploy_lnx
    - IMAGE_extend_cpu
    - IMAGE_extend_memory
    - IMAGE_resize_disk
    - OS_create_partition_lnx
    - IMAGE_reconfigure_network
    - UPDATE_hostvars
