---
- hosts: localhost
  gather_facts: no

  roles:
    - GITHUB

- hosts: [app01]
  gather_facts: no

  roles:
    - AD_group_add

- hosts: localhost
  gather_facts: no

  roles:
    - IMAGE_deploy_lnx
