---
- hosts: all
  gather_facts: no
  connection: local

  roles:
    - GITHUB
    - AD_group_add
    - IMAGE_deploy_lnx
    - IMAGE_extend_cpu
    - IMAGE_extend_memory
    - IMAGE_resize_disk
    - LNX_create_partition
    - IMAGE_reconfigure_network
    - ANSIBLE_update_hostvars
