---
- hosts: all
  gather_facts: no

  roles:
#    - GITHUB
    - AD_group_add
    - IMAGE_deploy_lnx
    - IMAGE_extend_cpu
    - IMAGE_extend_memory
    - IMAGE_virtual_disk_migration
    - IMAGE_attach_disk_persistent
    - IMAGE_resize_disk
    - IMAGE_additional_nic
    - LNX_create_partition
