---
#- hosts: [srv01]
- hosts: localhost
  gather_facts: no

  roles:
#    - AD_group_add
#    - AD_group_remove
#    - AD_join_win
#    - AD_rename_host_win
#    - AD_user_add
#    - AD_user_remove
#    - ANSIBLE_update_hostvars
#    - GITHUB
#    - IMAGE_deploy_lnx
#    - IMAGE_extend_cpu
#    - IMAGE_deploy_memory
#    - IMAGE_poweroff
#    - IMAGE_reconfigure_network
#    - IMAGE_remove_lnx
#    - IMAGE_resize_disk
#    - LNX_create_partition
#    - WIN_command
#    - WIN_copy_file
#    - WIN_copy_file_remote
#    - WIN_copy_folder
#    - WIN_copy_folder_remote
#    - WIN_dns_settings_add
#    - WIN_enable_secure_winrm
#    - WIN_environment_var_remove
#    - WIN_environment_var_set
#    - WIN_evententry_add
#    - WIN_enventlog_add
#    - WIN_facts
#    - WIN_feature_add
#    - WIN_feature_remove
#    - WIN_file_find
#    - WIN_file_get_version
#    - WIN_file_remove
#    - WIN_file_set
#    - WIN_file_touch
#    - WIN_folder_create
#    - WIN_folder_remove
#    - WIN_net35_add
#    - WIN_net35_remove
#    - WIN_workgroup_join
#    - WIN_workgroup_rename_host
